# Generated by Django 3.2.4 on 2021-07-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGUARETE_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
